import os

DATABASE_URI=os.environ['DATABASE_URI']
DATABASE_NAME= os.environ['DATABASE_NAME']
DATABASE_USERS=os.environ['DATABASE_USERS']
DATABASE_WEAPONS=os.environ['DATABASE_WEAPONS']
URLSAFE_KEY=os.environ['URLSAFE_KEY']
